controller_manager:
  ros__parameters:
    update_rate: 100
    switch_controller_timeout: 30.0
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    mobile_base_controller:
      type: diff_drive_controller/DiffDriveController

    arm_left_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_right_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_robotiq_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController

    right_robotiq_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController

head_controller:
  ros__parameters:
    joints:
      - head_1_joint
      - head_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    gains:
      head_1_joint:
        p: 0.0
        i: 0.0
        d: 0.0
      head_2_joint:
        p: 0.0
        i: 0.0
        d: 0.0

    interpolate_from_desired_state: true

    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 5.0
      head_1_joint:
        goal: 0.5
      head_2_joint:
        goal: 0.5

torso_controller:
  ros__parameters:
    joints:
      - torso_lift_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    gains:
      torso_lift_joint: {p: 0.0, i: 0.0, d: 0.0}

    interpolate_from_desired_state: true

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      torso_lift_joint: {goal: 0.02}

mobile_base_controller:
  ros__parameters:
    use_stamped_vel: true
    publish_limited_velocity: true
    publish_odom_tf: true

    left_wheel_names: ['wheel_left_joint']
    right_wheel_names: ['wheel_right_joint']

    wheel_radius: 0.0985
    wheel_separation: 0.4044

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    cmd_vel_timeout: 2.5
    odom_frame_id: odom
    base_frame_id: base_footprint
    # enable_odom_tf: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -0.5
        has_acceleration_limits: true
        max_acceleration: 1.5
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 2.5

arm_left_controller:
  ros__parameters:
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    gains:
      arm_left_1_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_left_2_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_left_3_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_left_4_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_left_5_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_left_6_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_left_7_joint: {p: 0.0, i: 0.0, d: 0.0}

    interpolate_from_desired_state: true

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      arm_left_1_joint: {goal: 0.02}
      arm_left_2_joint: {goal: 0.02}
      arm_left_3_joint: {goal: 0.02}
      arm_left_4_joint: {goal: 0.02}
      arm_left_5_joint: {goal: 0.02}
      arm_left_6_joint: {goal: 0.02}
      arm_left_7_joint: {goal: 0.02}

arm_right_controller:
  ros__parameters:
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    gains:
      arm_right_1_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_right_2_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_right_3_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_right_4_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_right_5_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_right_6_joint: {p: 0.0, i: 0.0, d: 0.0}
      arm_right_7_joint: {p: 0.0, i: 0.0, d: 0.0}

    interpolate_from_desired_state: true

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      arm_right_1_joint: {goal: 0.02}
      arm_right_2_joint: {goal: 0.02}
      arm_right_3_joint: {goal: 0.02}
      arm_right_4_joint: {goal: 0.02}
      arm_right_5_joint: {goal: 0.02}
      arm_right_6_joint: {goal: 0.02}
      arm_right_7_joint: {goal: 0.02}

left_robotiq_gripper_controller:
  ros__parameters:
    joint: gripper_left_finger_joint
    command_interface: position
    state_interfaces: ["position", "velocity"]
    allow_stalling: true
    stall_timeout: 0.05
    goal_tolerance: 0.02
 
right_robotiq_gripper_controller:
  ros__parameters:
    joint: gripper_right_finger_joint
    command_interface: position
    state_interfaces: ["position", "velocity"]
    allow_stalling: true
    stall_timeout: 0.05
    goal_tolerance: 0.02

