/**:
  ros__parameters:
    use_sim_time: true

    image_transport: raw
    family: "36h11"
    size: 0.152576

    max_hamming: 0

    pose_estimation_method: "pnp"

    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: true

    tag:
      ids: [0]
      frames: ["dock_apriltag"]
      sizes: [0.152576]