ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # -------------------------------------------------------------
    # Config order:
    # [x_pos   , y_pos    , z_pos,
    #  roll    , pitch    , yaw,
    #  x_vel   , y_vel    , z_vel,
    #  roll_vel, pitch_vel, yaw_vel,
    #  x_accel , y_accel  , z_accel]
    # -------------------------------------------------------------

    # Wheel Odometry: fuse linear velocities & angular velocity
    odom0: /mobile_base_controller/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  false, false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false

    # IMU: fuse orientation (yaw) and angular velocity
    imu0: /base_imu
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]